//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : FishingJoy
//  @ File Name : StaticData.h
//  @ Date : 2017/9/29
//  @ Author : linwei
//
//


#if !defined(_STATICDATA_H)
#define _STATICDATA_H


class StaticData {
public:
	static StaticData sharedStaticData();
	static void purge();
	int intValueFormKey(std::string key);
	char stringValueFormKey(std::sting key);
	float floatValueFormKey(std::string key);
	bool booleanFormKey(std::string key);
	cocos2d::CCPoint pointFormKey(std::string key);
	cocos2d::CCRect rectFormKey(std::string key);
	cocos2d::CCSize sizeFormKey(std::string key);
protected:
	cocos2d::CCDictionary _dictionary;
	// 	
	std::string _staticFileName;
	bool init();
private:
	~StaticData();
	StaticData();
};

#endif  //_STATICDATA_H
